name: Matkahuolto daily tracker

on:
  schedule:
    # GitHub cron is **UTC**. 09:00 & 16:00 in Helsinki (UTC+3 summer, +2 winter)
    - cron: '0 6 * * *'    # 09:00 EEST  / 08:00 EET
    - cron: '0 13 * * *'   # 16:00 EEST  / 15:00 EET
  workflow_dispatch:       # manual “Run workflow” button

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    env:                    # export secrets as env vars for the script
      MH_USER:             ${{ secrets.MH_USER }}
      MH_PASS:             ${{ secrets.MH_PASS }}
      TELEGRAM_TOKEN:      ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID:    ${{ secrets.TELEGRAM_CHAT_ID }}
      LOOKBACK_DAYS:       '5'
      STALE_BUSINESS_DAYS: '1'
      MH_TIMEOUT:          '90'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests workalendar python-telegram-bot==13.15

    - name: Run tracker
      run: python mh_tracker.py